INSERT INTO skills (skill_id, resume_id, skill_name, Proficiency_level, Certificate) VALUES
(1, 'RI1', 'Java', 'Expert', 'Oracle Certified Java Developer'),
(2, 'RI2', 'Machine Learning', 'Intermediate', 'Coursera ML by Andrew Ng'),
(3, 'RI3', 'SQL', 'Expert', 'SQL for Data Science (Udemy)'),
(4, 'RI4', 'Python', 'Expert', 'Python for Everybody (Coursera)'),
(5, 'RI5', 'Data Science', 'Intermediate', 'Google Data Analytics'),
(6, 'RI6', 'Cyber Security', 'Beginner', NULL),
(7, 'RI7', 'HTML & CSS', 'Expert', 'Responsive Web Design (freeCodeCamp)'),
(8, 'RI8', 'JavaScript', 'Intermediate', NULL),
(9, 'RI9', 'Blockchain', 'Beginner', 'Introduction to Blockchain (EdX)'),
(10, 'RI10', 'Artificial Intelligence', 'Expert', 'AI for Everyone (Coursera)'),
(11, 'RI11', 'Networking', 'Intermediate', 'Cisco CCNA'),
(12, 'RI12', 'Cloud Computing', 'Beginner', 'AWS Cloud Practitioner'),
(13, 'RI13', 'React.js', 'Intermediate', NULL),
(14, 'RI14', 'C++', 'Expert', NULL),
(15, 'RI15', 'Flutter', 'Intermediate', 'Flutter Developer Bootcamp (Udemy)'),
(16, 'RI16', 'Linux', 'Intermediate', 'Linux Administration (Udemy)'),
(17, 'RI17', 'Big Data', 'Beginner', 'Hadoop and Spark (EdX)'),
(18, 'RI18', 'IOT', 'Beginner', 'IoT Fundamentals (Cisco)'),
(19, 'RI19', 'Ethical Hacking', 'Intermediate', 'CEH (Certified Ethical Hacker)'),
(20, 'RI20', 'NLP', 'Expert', 'NLP Specialization (Coursera)'),
(21, 'RI21', 'Node.js', 'Expert', 'Node.js & Express (Udemy)'),
(22, 'RI22', 'Express.js', 'Intermediate', NULL),
(23, 'RI23', 'PHP', 'Beginner', 'PHP for Beginners (Udemy)'),
(24, 'RI24', 'R', 'Beginner', NULL),
(25, 'RI25', 'Kubernetes', 'Beginner', 'Kubernetes Basics (EdX)'),
(26, 'RI27', 'AR/VR Development', 'Beginner', 'AR/VR Basics (Coursera)'),
(27, 'RI28', 'Computer Vision', 'Intermediate', 'OpenCV & Deep Learning (Udemy)'),
(28, 'RI29', 'UI/UX Design', 'Intermediate', 'Adobe XD & Figma UI/UX (Udemy)'),
(29, 'RI30', 'Database Management System', 'Expert', 'Advanced DBMS (Udemy)'),
(30, 'RI31', 'SQL & NoSQL Databases', 'Expert', 'MongoDB & MySQL (Coursera)'),
(31, 'RI32', 'Operating System', 'Expert', 'Operating System Fundamentals (MIT)'),
(32, 'RI33', 'Firebase', 'Beginner', 'Firebase Basics (Google)'),
(33, 'RI34', 'Reverse Engineering', 'Beginner', 'Reverse Engineering Basics (Udemy)'),
(34, 'RI35', 'Java', 'Expert', 'Oracle Certified Java Developer'),
(35, 'RI36', 'Networking', 'Intermediate', 'Cisco CCNA'),
(36, 'RI37', 'Machine Learning', 'Beginner', NULL),
(37, 'RI38', 'Cyber Security', 'Intermediate', 'Ethical Hacking Course (Udemy)'),
(38, 'RI39', 'C++', 'Intermediate', 'C++ Programming (EdX)'),
(39, 'RI40', 'C', 'Expert', NULL),
(40, 'RI41', 'Cloud Computing', 'Intermediate', 'Google Cloud Fundamentals'),
(41, 'RI42', 'Software Development', 'Intermediate', 'Software Engineering (Coursera)'),
(42, 'RI43', 'Data Science', 'Beginner', NULL),
(43, 'RI44', 'NLP', 'Intermediate', 'NLP in Python (Udemy)'),
(44, 'RI45', 'SQL', 'Intermediate', 'Advanced SQL (Codecademy)'),
(45, 'RI46', 'Linux', 'Expert', 'Red Hat Certified Engineer'),
(46, 'RI47', 'Blockchain', 'Beginner', 'Blockchain Basics (IBM)'),
(47, 'RI48', 'Cyber Security', 'Expert', 'Ethical Hacking Course (Udemy)'),
(48, 'RI49', 'HTML & CSS', 'Beginner', 'Web Development Bootcamp'),
(49, 'RI50', 'Networking', 'Expert', 'Cisco CCNA'),
(50, 'RI51', 'JavaScript', 'Expert', 'JavaScript Mastery (Udemy)'),
(51, 'RI52', 'Python', 'Expert', 'Python DS (Coursera)'),
(52, 'RI53', 'React.js', 'Intermediate', 'Full Stack React (Udemy)'),
(53, 'RI54', 'Flutter', 'Beginner', NULL),
(54, 'RI55', 'IOT', 'Expert', NULL),
(55, 'RI56', 'C++', 'Intermediate', 'C++ Programming (EdX)'),
(56, 'RI57', 'Cloud Computing', 'Expert', 'Google Cloud Fundamentals'),
(57, 'RI58', 'Artificial Intelligence', 'Beginner', 'AI for Everyone (Coursera)'),
(58, 'RI59', 'Big Data', 'Expert', 'Hadoop and Spark (Cloudera)'),
(59, 'RI60', 'Edge Computing', 'Intermediate', 'Edge AI & IOT (Udemy)'),
(60, 'RI61', 'Data Warehousing', 'Beginner', 'Data Warehousing Concepts (Udemy)'),
(61, 'RI62', 'Shell Scripting', 'Intermediate', 'Bash Shell Scripting (Udemy)'),
(62, 'RI63', 'PostgreSQL', 'Intermediate', 'PostgreSQL for Developers (Udemy)'),
(63, 'RI64', 'Firebase', 'Beginner', 'Firebase Basics (Google)'),
(64, 'RI65', 'Operating System', 'Expert', 'Operating System Fundamentals (MIT)'),
(65, 'RI66', 'Robotics', 'Beginner', 'Introduction to Robotics (MIT)'),
(66, 'RI67', 'Game Development', 'Beginner', 'Unity Game Development (Udemy)'),
(67, 'RI68', 'Git & GitHub', 'Expert', 'GitHub Actions & CI/CD (Udemy)'),
(68, 'RI69', 'Competitive Programming', 'Intermediate', NULL),
(69, 'RI70', 'System Design', 'Intermediate', NULL),
(70, 'RI71', 'Express.js', 'Expert', NULL),
(71, 'RI72', 'C++', 'Expert', 'C++ Programming (Udemy)'),
(72, 'RI73', 'Data Science', 'Beginner', NULL),
(73, 'RI74', 'Machine Learning', 'Beginner', NULL),
(74, 'RI75', 'Java', 'Intermediate', 'Java Programming (Udacity)'),
(75, 'RI76', 'Python', 'Expert', 'Python DS (Coursera)'),
(76, 'RI77', 'SQL', 'Intermediate', 'Advanced SQL (Codecademy)'),
(77, 'RI78', 'Blockchain', 'Intermediate', 'Blockchain Basics (IBM)'),
(78, 'RI79', 'NLP', 'Expert', 'NLP in Python (Udemy)'),
(79, 'RI80', 'Reverse Engineering', 'Expert', 'Reverse Engineering Basics (Udemy)'),
(80, 'RI81', 'UI/UX Design', 'Beginner', 'Adobe XD & Figma UI/UX (Udemy)'),
(81, 'RI82', 'Node.js', 'Expert', 'Node.js & Express (Udemy)'),
(82, 'RI83', 'Networking', 'Intermediate', NULL),
(83, 'RI84', 'Bootstrap', 'Expert', 'Bootstrap 5 Basics (Udemy)'),
(84, 'RI85', 'HTML & CSS', 'Expert', 'Web Development Bootcamp'),
(85, 'RI86', 'Artificial Intelligence', 'Beginner', NULL),
(86, 'RI87', 'Data Science', 'Beginner', NULL),
(87, 'RI88', 'Java', 'Intermediate', 'Java Programming (Udacity)'),
(88, 'RI89', 'Kubernetes', 'Expert', 'Kubernetes Basics (EdX)'),
(89, 'RI90', 'Ethical Hacking', 'Beginner', NULL),
(90, 'RI91', 'Big Data', 'Intermediate', 'Hadoop and Spark (Cloudera)'),
(91, 'RI92', 'Rest API', 'Expert', 'REST API Development (Udemy)'),
(92, 'RI93', 'C++', 'Expert', 'C++ Programming (EdX)'),
(93, 'RI94', 'JavaScript', 'Expert', NULL),
(94, 'RI100', 'HTML & CSS', 'Expert', 'Web Development Bootcamp'),
(95, 'RI96', 'Cyber Security', 'Intermediate', 'Ethical Hacking Course (Udemy)'),
(96, 'RI97', 'IOT', 'Expert', 'IOT Security (Udemy)'),
(97, 'RI98', 'R', 'Expert', NULL),
(98, 'RI99', 'Flask', 'Intermediate', NULL),
(99, 'RI100', 'Game Development', 'Beginner', 'Unity Game Development (Udemy)'),
(100, 'RI26', 'HTML & CSS', 'Expert', 'Web Development Bootcamp');