INSERT INTO resume (resume_id, user_id, languages_known, achievements) VALUES
('RI1', 84, 'French, Mandarin, German', 'Published Research Paper'),
('RI2', 54, 'English, German, French', 'Top Performer in College'),
('RI3', 71, 'English, Spanish', 'Published Research Paper'),
('RI4', 46, 'French', 'Patent Holder'),
('RI5', 45, 'Spanish', 'Published Research Paper'),
('RI6', 40, 'French', 'Patent Holder'),
('RI7', 23, 'German, Spanish, English', 'Patent Holder'),
('RI8', 81, 'French, German', 'Patent Holder'),
('RI9', 11, 'Spanish, English', 'Top Performer in College'),
('RI10', 1, 'Spanish, German', 'Winner of Hackathon'),
('RI11', 19, 'English', 'Developed an App'),
('RI12', 31, 'Mandarin, Spanish', 'Certified in AI'),
('RI13', 74, 'Mandarin, German', 'Developed an App'),
('RI14', 34, 'English, Spanish', 'Published Research Paper'),
('RI15', 91, 'Spanish, French', 'Certified in AI'),
('RI16', 5, 'English, Hindi', 'Developed an App'),
('RI17', 77, 'Mandarin', 'Certified in AI'),
('RI18', 78, 'German, Hindi', 'Certified in AI'),
('RI19', 13, 'Hindi', 'Patent Holder'),
('RI20', 32, 'English', 'Patent Holder'),
('RI21', 56, 'German, Mandarin, Spanish', 'Patent Holder'),
('RI22', 89, 'Spanish, English, French', 'Certified in AI'),
('RI23', 27, 'Mandarin', 'Developed an App'),
('RI24', 43, 'Mandarin, Spanish, German', 'Patent Holder'),
('RI25', 70, 'German', 'Developed an App'),
('RI26', 16, 'French, Spanish', 'Certified in AI'),
('RI27', 41, 'German', 'Winner of Hackathon'),
('RI28', 97, 'Spanish, Mandarin', 'Published Research Paper'),
('RI29', 10, 'French', 'Patent Holder'),
('RI30', 73, 'Spanish, German, French', 'Winner of Hackathon'),
('RI31', 12, 'Spanish', 'Winner of Hackathon'),
('RI32', 48, 'Hindi', 'Patent Holder'),
('RI33', 86, 'English', 'Published Research Paper'),
('RI34', 29, 'English', 'Top Performer in College'),
('RI35', 94, 'Hindi, German', 'Winner of Hackathon'),
('RI36', 6, 'German, French, Mandarin', 'Top Performer in College'),
('RI37', 67, 'Hindi', 'Published Research Paper'),
('RI38', 66, 'German', 'Developed an App'),
('RI39', 36, 'English, German', 'Top Performer in College'),
('RI40', 17, 'English', 'Top Performer in College'),
('RI41', 50, 'French', 'Winner of Hackathon'),
('RI42', 35, 'Spanish', 'Patent Holder'),
('RI43', 8, 'German, Hindi, Mandarin', 'Developed an App'),
('RI44', 96, 'French, Mandarin, German', 'Winner of Hackathon'),
('RI45', 28, 'French, English, German', 'Patent Holder'),
('RI46', 20, 'Spanish, Hindi, English', 'Published Research Paper'),
('RI47', 82, 'Hindi', 'Developed an App'),
('RI48', 26, 'Hindi, German, French', 'Developed an App'),
('RI49', 63, 'English', 'Top Performer in College'),
('RI50', 14, 'Spanish, French', 'Certified in AI'),
('RI51', 25, 'English', 'Developed an App'),
('RI52', 4, 'French', 'Certified in AI'),
('RI53', 18, 'English', 'Winner of Hackathon'),
('RI54', 39, 'French, English', 'Top Performer in College'),
('RI55', 9, 'French, Spanish', 'Winner of Hackathon'),
('RI56', 79, 'Hindi', 'Winner of Hackathon'),
('RI57', 7, 'German, Spanish, Hindi', 'Certified in AI'),
('RI58', 65, 'German, English', 'Winner of Hackathon'),
('RI59', 37, 'French, German', 'Developed an App'),
('RI60', 90, 'French', 'Certified in AI'),
('RI61', 57, 'English, Spanish', 'Certified in AI'),
('RI62', 100, 'Spanish, Hindi, Mandarin', 'Certified in AI'),
('RI63', 55, 'Mandarin, French', 'Certified in AI'),
('RI64', 44, 'French', 'Top Performer in College'),
('RI65', 51, 'German', 'Certified in AI'),
('RI66', 68, 'Mandarin', 'Published Research Paper'),
('RI67', 47, 'French, Mandarin', 'Top Performer in College'),
('RI68', 69, 'Spanish, French, English', 'Developed an App'),
('RI69', 62, 'French', 'Certified in AI'),
('RI70', 98, 'Mandarin', 'Winner of Hackathon'),
('RI71', 80, 'Mandarin, English', 'Winner of Hackathon'),
('RI72', 42, 'Hindi, English, Mandarin', 'Winner of Hackathon'),
('RI73', 59, 'Hindi', 'Developed an App'),
('RI74', 49, 'French', 'Certified in AI'),
('RI75', 99, 'English, French', 'Certified in AI'),
('RI76', 58, 'Hindi, Spanish, French', 'Published Research Paper'),
('RI77', 76, 'English, Spanish, German', 'Patent Holder'),
('RI78', 33, 'German, Spanish, Mandarin', 'Published Research Paper'),
('RI79', 95, 'Spanish, German', 'Patent Holder'),
('RI80', 60, 'Hindi, English, Spanish', 'Published Research Paper'),
('RI81', 64, 'German, Mandarin', 'Top Performer in College'),
('RI82', 85, 'Mandarin, German', 'Winner of Hackathon'),
('RI83', 38, 'Hindi', 'Winner of Hackathon'),
('RI84', 30, 'French, English, Spanish', 'Developed an App'),
('RI85', 2, 'Mandarin', 'Winner of Hackathon'),
('RI86', 53, 'English', 'Winner of Hackathon'),
('RI87', 22, 'Hindi', 'Certified in AI'),
('RI88', 3, 'Mandarin, French, English', 'Patent Holder'),
('RI89', 24, 'German', 'Patent Holder'),
('RI90', 88, 'Spanish, German, Mandarin', 'Published Research Paper'),
('RI91', 92, 'Mandarin, French, English', 'Patent Holder'),
('RI92', 75, 'French, Mandarin, Spanish', 'Winner of Hackathon'),
('RI93', 87, 'Spanish, French', 'Developed an App'),
('RI94', 83, 'Spanish, German', 'Developed an App'),
('RI95', 21, 'Hindi, Spanish', 'Certified in AI'),
('RI96', 61, 'German, French', 'Winner of Hackathon'),
('RI97', 72, 'Hindi, Spanish', 'Published Research Paper'),
('RI98', 15, 'Mandarin, English, German', 'Top Performer in College'),
('RI99', 93, 'Spanish', 'Winner of Hackathon'),
('RI100', 52, 'French, Hindi, German', 'Published Research Paper');