INSERT INTO project (project_id, resume_id, project_title, project_description, technologies_used) VALUES
(1, 'RI79', 'Hospital Management System', 'This project focuses on hospital management system using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(2, 'RI44', 'E-commerce Website', 'This project focuses on e-commerce website using cutting-edge technologies.', 'AWS, Kubernetes, Terraform'),
(3, 'RI14', 'Online Learning Platform', 'This project focuses on online learning platform using cutting-edge technologies.', 'Unity, C#, VR'),
(4, 'RI97', 'Self-driving Car Simulation', 'This project focuses on self-driving car simulation using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(5, 'RI43', 'AI Chatbot', 'This project focuses on ai chatbot using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(6, 'RI21', 'Sentiment Analysis Tool', 'This project focuses on sentiment analysis tool using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(7, 'RI18', 'E-commerce Website', 'This project focuses on e-commerce website using cutting-edge technologies.', 'Golang, GraphQL, Redis'),
(8, 'RI49', 'Augmented Reality Shopping', 'This project focuses on augmented reality shopping using cutting-edge technologies.', 'Unity, C#, VR'),
(9, 'RI96', 'Smart Home Automation', 'This project focuses on smart home automation using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(10, 'RI61', 'Cryptocurrency Price Predictor', 'This project focuses on cryptocurrency price predictor using cutting-edge technologies.', 'Angular, Firebase, TypeScript'),
(11, 'RI64', 'Face Recognition System', 'This project focuses on face recognition system using cutting-edge technologies.', 'Golang, GraphQL, Redis'),
(12, 'RI1', 'Virtual Reality Game', 'This project focuses on virtual reality game using cutting-edge technologies.', 'Unity, C#, VR'),
(13, 'RI6', 'AI-powered Resume Screener', 'This project focuses on ai-powered resume screener using cutting-edge technologies.', 'Golang, GraphQL, Redis'),
(14, 'RI10', 'Weather Forecasting App', 'This project focuses on weather forecasting app using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(15, 'RI61', 'E-commerce Website', 'This project focuses on e-commerce website using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(16, 'RI84', 'Inventory Management System', 'This project focuses on inventory management system using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(17, 'RI26', 'Cloud File Storage', 'This project focuses on cloud file storage using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(18, 'RI36', 'Hospital Management System', 'This project focuses on hospital management system using cutting-edge technologies.', 'Django, PostgreSQL, Docker'),
(19, 'RI74', 'Smart Home Automation', 'This project focuses on smart home automation using cutting-edge technologies.', 'Python, TensorFlow, Flask'),
(20, 'RI59', 'Autonomous Drone Navigation', 'This project focuses on autonomous drone navigation using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(21, 'RI23', 'Inventory Management System', 'This project focuses on inventory management system using cutting-edge technologies.', 'Unity, C#, VR'),
(22, 'RI58', 'Cryptocurrency Price Predictor', 'This project focuses on cryptocurrency price predictor using cutting-edge technologies.', 'Unity, C#, VR'),
(23, 'RI8', 'E-commerce Website', 'This project focuses on e-commerce website using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(24, 'RI14', 'Smart Home Automation', 'This project focuses on smart home automation using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(25, 'RI32', 'Inventory Management System', 'This project focuses on inventory management system using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(26, 'RI41', 'AI Chatbot', 'This project focuses on ai chatbot using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(27, 'RI64', 'Augmented Reality Shopping', 'This project focuses on augmented reality shopping using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(28, 'RI43', 'Sentiment Analysis Tool', 'This project focuses on sentiment analysis tool using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(29, 'RI58', 'Cybersecurity Threat Detector', 'This project focuses on cybersecurity threat detector using cutting-edge technologies.', 'Django, PostgreSQL, Docker'),
(30, 'RI36', 'IoT-based Health Monitoring', 'This project focuses on iot-based health monitoring using cutting-edge technologies.', 'Golang, GraphQL, Redis'),
(31, 'RI46', 'Cloud File Storage', 'This project focuses on cloud file storage using cutting-edge technologies.', 'Raspberry Pi, IoT, MQTT'),
(32, 'RI82', 'Cloud File Storage', 'This project focuses on cloud file storage using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(33, 'RI14', 'Cybersecurity Threat Detector', 'This project focuses on cybersecurity threat detector using cutting-edge technologies.', 'Raspberry Pi, IoT, MQTT'),
(34, 'RI68', 'Virtual Reality Game', 'This project focuses on virtual reality game using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(35, 'RI91', 'Weather Forecasting App', 'This project focuses on weather forecasting app using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(36, 'RI42', 'Cloud File Storage', 'This project focuses on cloud file storage using cutting-edge technologies.', 'Golang, GraphQL, Redis'),
(37, 'RI62', 'Sentiment Analysis Tool', 'This project focuses on sentiment analysis tool using cutting-edge technologies.', 'Python, TensorFlow, Flask'),
(38, 'RI93', 'Cybersecurity Threat Detector', 'This project focuses on cybersecurity threat detector using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(39, 'RI89', 'IoT-based Health Monitoring', 'This project focuses on iot-based health monitoring using cutting-edge technologies.', 'Python, TensorFlow, Flask'),
(40, 'RI21', 'Self-driving Car Simulation', 'This project focuses on self-driving car simulation using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(41, 'RI27', 'AI Chatbot', 'This project focuses on ai chatbot using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(42, 'RI64', 'Hospital Management System', 'This project focuses on hospital management system using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(43, 'RI90', 'Inventory Management System', 'This project focuses on inventory management system using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(44, 'RI84', 'Stock Market Analysis Tool', 'This project focuses on stock market analysis tool using cutting-edge technologies.', 'Unity, C#, VR'),
(45, 'RI74', 'Online Learning Platform', 'This project focuses on online learning platform using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(46, 'RI66', 'AI Chatbot', 'This project focuses on ai chatbot using cutting-edge technologies.', 'Python, TensorFlow, Flask'),
(47, 'RI99', 'AI Chatbot', 'This project focuses on ai chatbot using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(48, 'RI28', 'Blockchain Voting System', 'This project focuses on blockchain voting system using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(49, 'RI34', 'Hospital Management System', 'This project focuses on hospital management system using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(50, 'RI57', 'AI-powered Resume Screener', 'This project focuses on ai-powered resume screener using cutting-edge technologies.', 'AWS, Kubernetes, Terraform'),
(51, 'RI69', 'AI Chatbot', 'This project focuses on ai chatbot using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(52, 'RI32', 'Virtual Reality Game', 'This project focuses on virtual reality game using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(53, 'RI70', 'Online Learning Platform', 'This project focuses on online learning platform using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(54, 'RI63', 'Cybersecurity Threat Detector', 'This project focuses on cybersecurity threat detector using cutting-edge technologies.', 'AWS, Kubernetes, Terraform'),
(55, 'RI68', 'Online Learning Platform', 'This project focuses on online learning platform using cutting-edge technologies.', 'Raspberry Pi, IoT, MQTT'),
(56, 'RI91', 'Sentiment Analysis Tool', 'This project focuses on sentiment analysis tool using cutting-edge technologies.', 'Angular, Firebase, TypeScript'),
(57, 'RI81', 'Inventory Management System', 'This project focuses on inventory management system using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(58, 'RI47', 'Face Recognition System', 'This project focuses on face recognition system using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(59, 'RI11', 'Self-driving Car Simulation', 'This project focuses on self-driving car simulation using cutting-edge technologies.', 'Raspberry Pi, IoT, MQTT'),
(60, 'RI28', 'Blockchain Voting System', 'This project focuses on blockchain voting system using cutting-edge technologies.', 'Unity, C#, VR'),
(61, 'RI99', 'Inventory Management System', 'This project focuses on inventory management system using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(62, 'RI90', 'Cloud File Storage', 'This project focuses on cloud file storage using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(63, 'RI87', 'Smart Home Automation', 'This project focuses on smart home automation using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(64, 'RI33', 'AI Chatbot', 'This project focuses on ai chatbot using cutting-edge technologies.', 'AWS, Kubernetes, Terraform'),
(65, 'RI50', 'Cryptocurrency Price Predictor', 'This project focuses on cryptocurrency price predictor using cutting-edge technologies.', 'Angular, Firebase, TypeScript'),
(66, 'RI40', 'Autonomous Drone Navigation', 'This project focuses on autonomous drone navigation using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(67, 'RI81', 'Cybersecurity Threat Detector', 'This project focuses on cybersecurity threat detector using cutting-edge technologies.', 'Raspberry Pi, IoT, MQTT'),
(68, 'RI6', 'Hospital Management System', 'This project focuses on hospital management system using cutting-edge technologies.', 'Django, PostgreSQL, Docker'),
(69, 'RI10', 'Self-driving Car Simulation', 'This project focuses on self-driving car simulation using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(70, 'RI91', 'Stock Market Analysis Tool', 'This project focuses on stock market analysis tool using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(71, 'RI47', 'Sentiment Analysis Tool', 'This project focuses on sentiment analysis tool using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(72, 'RI87', 'Smart Home Automation', 'This project focuses on smart home automation using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(73, 'RI94', 'Online Learning Platform', 'This project focuses on online learning platform using cutting-edge technologies.', 'Golang, GraphQL, Redis'),
(74, 'RI98', 'Weather Forecasting App', 'This project focuses on weather forecasting app using cutting-edge technologies.', 'Raspberry Pi, IoT, MQTT'),
(75, 'RI65', 'Inventory Management System', 'This project focuses on inventory management system using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(76, 'RI71', 'E-commerce Website', 'This project focuses on e-commerce website using cutting-edge technologies.', 'AWS, Kubernetes, Terraform'),
(77, 'RI44', 'IoT-based Health Monitoring', 'This project focuses on iot-based health monitoring using cutting-edge technologies.', 'Unity, C#, VR'),
(78, 'RI96', 'AI-powered Resume Screener', 'This project focuses on ai-powered resume screener using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(79, 'RI78', 'Autonomous Drone Navigation', 'This project focuses on autonomous drone navigation using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(80, 'RI69', 'IoT-based Health Monitoring', 'This project focuses on iot-based health monitoring using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(81, 'RI53', 'Stock Market Analysis Tool', 'This project focuses on stock market analysis tool using cutting-edge technologies.', 'AWS, Kubernetes, Terraform'),
(82, 'RI55', 'Hospital Management System', 'This project focuses on hospital management system using cutting-edge technologies.', 'Python, TensorFlow, Flask'),
(83, 'RI47', 'Cryptocurrency Price Predictor', 'This project focuses on cryptocurrency price predictor using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(84, 'RI76', 'Cryptocurrency Price Predictor', 'This project focuses on cryptocurrency price predictor using cutting-edge technologies.', 'React, Node.js, MongoDB'),
(85, 'RI2', 'Stock Market Analysis Tool', 'This project focuses on stock market analysis tool using cutting-edge technologies.', 'Raspberry Pi, IoT, MQTT'),
(86, 'RI75', 'Augmented Reality Shopping', 'This project focuses on augmented reality shopping using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(87, 'RI54', 'Hospital Management System', 'This project focuses on hospital management system using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(88, 'RI96', 'Smart Home Automation', 'This project focuses on smart home automation using cutting-edge technologies.', 'Angular, Firebase, TypeScript'),
(89, 'RI16', 'Augmented Reality Shopping', 'This project focuses on augmented reality shopping using cutting-edge technologies.', 'Python, TensorFlow, Flask'),
(90, 'RI85', 'E-commerce Website', 'This project focuses on e-commerce website using cutting-edge technologies.', 'Django, PostgreSQL, Docker'),
(91, 'RI94', 'Blockchain Voting System', 'This project focuses on blockchain voting system using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(92, 'RI1', 'AI Chatbot', 'This project focuses on ai chatbot using cutting-edge technologies.', 'Raspberry Pi, IoT, MQTT'),
(93, 'RI6', 'Online Learning Platform', 'This project focuses on online learning platform using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(94, 'RI86', 'Autonomous Drone Navigation', 'This project focuses on autonomous drone navigation using cutting-edge technologies.', 'Django, PostgreSQL, Docker'),
(95, 'RI22', 'Virtual Reality Game', 'This project focuses on virtual reality game using cutting-edge technologies.', 'Swift, iOS, CoreML'),
(96, 'RI10', 'Blockchain Voting System', 'This project focuses on blockchain voting system using cutting-edge technologies.', 'Java, Spring Boot, MySQL'),
(97, 'RI15', 'Virtual Reality Game', 'This project focuses on virtual reality game using cutting-edge technologies.', 'C++, OpenCV, Machine Learning'),
(98, 'RI43', 'Cybersecurity Threat Detector', 'This project focuses on cybersecurity threat detector using cutting-edge technologies.', 'Kotlin, Android, Jetpack'),
(99, 'RI20', 'IoT-based Health Monitoring', 'This project focuses on iot-based health monitoring using cutting-edge technologies.', 'Angular, Firebase, TypeScript'),
(100, 'RI21', 'E-commerce Website', 'This project focuses on e-commerce website using cutting-edge technologies.', 'Java, Spring Boot, MySQL');